'use strict';

const tableName = 'games';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    const { STRING, INTEGER, DATE, JSON, JSONB } = Sequelize;

    await queryInterface.createTable(
      tableName,
      {
        id: {
          type: INTEGER,
          primaryKey: true,
          autoIncrement: true,
          comment: 'id',
        },
        name: {
          type: STRING(100),
          allowNull: false,
          comment: '游戏名称',
        },
        type: {
          type: STRING(50),
          allowNull: false,
          comment:
            '游戏类型: standardDouDiZhu, standardPaoDeKuai, douDiZhu4Player, standardGuanDan, standardZhengShangYou, standard3Played510K, custom',
        },
        desc: {
          type: STRING(200),
          allowNull: true,
          comment: '描述',
        },
        direction: {
          type: STRING(20),
          allowNull: true,
          comment: '方向: up/left/right 等',
        },
        game_rule: {
          type: STRING(100),
          allowNull: false,
          comment:
            '规则: RuleStandardDouDiZhu, RuleDouDiZhu4Player, RuleStandardGuanDan, RuleStandardPaoDeKuai, RuleCustom',
        },
        move_generator: {
          type: STRING(100),
          allowNull: true,
          comment:
            '出牌生成器: CustomMoveGenerator, Standard3Played510KMoveGenerator, DouDiZhu4PlayedMoveGenerator, PaoDeKuaiMoveGenerator, AnyMoveGenerator',
        },
        card_num: {
          type: INTEGER,
          allowNull: false,
          defaultValue: 54,
          comment: '牌数',
        },
        player_num: {
          type: INTEGER,
          allowNull: false,
          comment: '玩家人数',
        },
        info_card_counts: {
          type: JSONB,
          allowNull: true,
          comment: '信息牌计数映射: { "<string>": <int> }',
        },
        areas: {
          type: JSONB,
          allowNull: true,
          comment:
            '区域数组: [{ minX, minY, width, height, type }], type: selfHand/selfDiscard/upperPlayerDiscard/lowerPlayerDiscard/oppositePlayerDiscard/fixed/other',
        },
        backgrounds: {
          type: JSON,
          allowNull: true,
          comment: '背景相对路径数组',
        },
        logo_path: {
          type: STRING(255),
          allowNull: true,
          comment: 'logo 相对路径',
        },
        version: {
          type: INTEGER,
          allowNull: false,
          defaultValue: 1,
          comment: '版本号',
        },
        support_app_version: {
          type: INTEGER,
          allowNull: true,
          comment: '支持的 App 版本',
        },
        created_at: {
          type: DATE,
          allowNull: false,
          defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
          comment: '创建时间',
        },
        updated_at: {
          type: DATE,
          allowNull: false,
          comment: '更新时间',
        },
      },
      {
        charset: 'utf8mb4',
        collate: 'utf8mb4_unicode_ci',
      },
    );

    await queryInterface.addIndex(tableName, ['name'], { unique: true });
    await queryInterface.addIndex(tableName, ['type']);
    await queryInterface.addIndex(tableName, ['version']);
    await queryInterface.addIndex(tableName, ['support_app_version']);

    const initData = [
      {
        name: '经典斗地主',
        type: 'standardDouDiZhu',
        desc: '经典三人斗地主',
        direction: 'right',
        game_rule: 'RuleStandardDouDiZhu',
        move_generator: 'CustomMoveGenerator',
        card_num: 54,
        player_num: 3,
        info_card_counts: JSON.stringify({
          "大王": 1,
          "小王": 1,
          "2": 4,
          "A": 4,
          "K": 4,
          "Q": 4,
          "J": 4,
          "10": 4,
          "9": 4,
          "8": 4,
          "7": 4,
          "6": 4,
          "5": 4,
          "4": 4,
          "3": 4,
        }),
        areas: JSON.stringify([
          {
            type: 'selfDiscard',
            minX: 0.3,
            minY: 0.38,
            width: 0.5,
            height: 0.19,
          },
          {
            type: 'selfHand',
            minX: 0.02,
            minY: 0.59,
            width: 0.96,
            height: 0.33,
          },
          {
            type: 'upperPlayerDiscard',
            minX: 0.1,
            minY: 0.12,
            width: 0.39,
            height: 0.25,
          },
          {
            type: 'lowerPlayerDiscard',
            minX: 0.51,
            minY: 0.12,
            width: 0.39,
            height: 0.25,
          },
        ]),
        backgrounds: JSON.stringify([
          'apps/backgrounds/bg_doudizhu_001.jpg',
          'apps/backgrounds/bg_doudizhu_002.jpg',
          'apps/backgrounds/bg_doudizhu_003.jpg',
          'apps/backgrounds/bg_doudizhu_004.jpg',
          'apps/backgrounds/bg_doudizhu_005.jpg',
          'apps/backgrounds/bg_doudizhu_006.jpg',
          'apps/backgrounds/bg_doudizhu_007.jpg',
          'apps/backgrounds/bg_doudizhu_008.jpg',
          'apps/backgrounds/bg_doudizhu_009.jpg',
          'apps/backgrounds/bg_doudizhu_010.jpg',
          'apps/backgrounds/bg_tuyou_doudizhu_001.jpg',
        ]),
        logo_path: 'apps/games/doudizhu.jpg',
        version: 1,
        support_app_version: 2,
      },
      {
        name: '经典跑得快',
        type: 'standardPaoDeKuai',
        desc: '经典三人跑得快',
        direction: 'right',
        game_rule: 'RuleCustom',
        move_generator: 'PaoDeKuaiMoveGenerator',
        card_num: 48,
        player_num: 3,
        info_card_counts: JSON.stringify({
          "大王": 0,
          "小王": 0,
          "2": 1,
          "A": 3,
          "K": 4,
          "Q": 4,
          "J": 4,
          "10": 4,
          "9": 4,
          "8": 4,
          "7": 4,
          "6": 4,
          "5": 4,
          "4": 4,
          "3": 4,
        }),
        areas: JSON.stringify([
          {
            type: 'selfDiscard',
            minX: 0.3,
            minY: 0.38,
            width: 0.5,
            height: 0.19,
          },
          {
            type: 'selfHand',
            minX: 0.02,
            minY: 0.59,
            width: 0.96,
            height: 0.33,
          },
          {
            type: 'upperPlayerDiscard',
            minX: 0.1,
            minY: 0.12,
            width: 0.39,
            height: 0.25,
          },
          {
            type: 'lowerPlayerDiscard',
            minX: 0.51,
            minY: 0.12,
            width: 0.39,
            height: 0.25,
          },
        ]),
        backgrounds: JSON.stringify(['apps/backgrounds/bg_doudizhu_001.jpg']),
        logo_path: 'apps/games/paodekuai.jpg',
        version: 1,
        support_app_version: 2,
      },
      {
        name: '四人斗地主',
        type: 'douDiZhu4Player',
        desc: '经典四人四人斗地主',
        direction: 'right',
        game_rule: 'RuleDouDiZhu4Player',
        move_generator: 'DouDiZhu4PlayedMoveGenerator',
        card_num: 108,
        player_num: 4,
        info_card_counts: JSON.stringify({
          "大王": 2,
          "小王": 2,
          "2": 8,
          "A": 8,
          "K": 8,
          "Q": 8,
          "J": 8,
          "10": 8,
          "9": 8,
          "8": 8,
          "7": 8,
          "6": 8,
          "5": 8,
          "4": 8,
          "3": 8,
        }),
        areas: JSON.stringify([
          {
            type: 'selfDiscard',
            minX: 0.3,
            minY: 0.38,
            width: 0.5,
            height: 0.19,
          },
          {
            type: 'selfHand',
            minX: 0.02,
            minY: 0.59,
            width: 0.96,
            height: 0.33,
          },
          {
            type: 'oppositePlayerDiscard',
            minX: 0.25,
            minY: 0.02,
            width: 0.35,
            height: 0.18,
          },
          {
            type: 'upperPlayerDiscard',
            minX: 0.13,
            minY: 0.21,
            width: 0.35,
            height: 0.11,
          },
          {
            type: 'lowerPlayerDiscard',
            minX: 0.52,
            minY: 0.21,
            width: 0.35,
            height: 0.11,
          },
        ]),
        backgrounds: JSON.stringify(['apps/backgrounds/bg_doudizhu_001.jpg']),
        logo_path: 'apps/games/guandan.jpg',
        version: 1,
        support_app_version: 2,
      },
      {
        name: '三人510K',
        type: 'standard3Played510K',
        desc: '经典 三人510K',
        direction: 'right',
        game_rule: 'RuleCustom',
        move_generator: 'Standard3Played510KMoveGenerator',
        card_num: 54,
        player_num: 3,
        info_card_counts: JSON.stringify({
          "大王": 1,
          "小王": 1,
          "2": 4,
          "A": 4,
          "K": 4,
          "Q": 4,
          "J": 4,
          "10": 4,
          "9": 4,
          "8": 4,
          "7": 4,
          "6": 4,
          "5": 4,
          "4": 4,
          "3": 4,
        }),
        areas: JSON.stringify([
          {
            type: 'selfDiscard',
            minX: 0.3,
            minY: 0.38,
            width: 0.5,
            height: 0.19,
          },
          {
            type: 'selfHand',
            minX: 0.02,
            minY: 0.59,
            width: 0.96,
            height: 0.33,
          },
          {
            type: 'upperPlayerDiscard',
            minX: 0.1,
            minY: 0.12,
            width: 0.39,
            height: 0.25,
          },
          {
            type: 'lowerPlayerDiscard',
            minX: 0.51,
            minY: 0.12,
            width: 0.39,
            height: 0.25,
          },
        ]),
        backgrounds: JSON.stringify(['apps/backgrounds/bg_doudizhu_001.jpg']),
        logo_path: 'apps/games/510K.png',
        version: 1,
        support_app_version: 2,
      },
      {
        name: '自定义',
        type: 'standardPaoDeKuai',
        desc: '自定义游戏',
        direction: 'right',
        game_rule: 'RuleCustom',
        move_generator: 'AnyMoveGenerator',
        card_num: 54,
        player_num: 3,
        info_card_counts: JSON.stringify({
          "大王": 1,
          "小王": 1,
          "2": 4,
          "A": 4,
          "K": 4,
          "Q": 4,
          "J": 4,
          "10": 4,
          "9": 4,
          "8": 4,
          "7": 4,
          "6": 4,
          "5": 4,
          "4": 4,
          "3": 4,
        }),
        areas: JSON.stringify([
          {
            type: 'selfDiscard',
            minX: 0.3,
            minY: 0.38,
            width: 0.5,
            height: 0.19,
          },
          {
            type: 'selfHand',
            minX: 0.02,
            minY: 0.59,
            width: 0.96,
            height: 0.33,
          },
          {
            type: 'upperPlayerDiscard',
            minX: 0.1,
            minY: 0.12,
            width: 0.39,
            height: 0.25,
          },
          {
            type: 'lowerPlayerDiscard',
            minX: 0.51,
            minY: 0.12,
            width: 0.39,
            height: 0.25,
          },
        ]),
        backgrounds: JSON.stringify(['apps/backgrounds/bg_doudizhu_001.jpg']),
        logo_path: 'apps/games/custom.jpg',
        version: 1,
        support_app_version: 2
      },
    ];

    await queryInterface.bulkInsert(tableName, initData);
  },

  down: async (queryInterface) => {
    return queryInterface.dropTable(tableName);
  },
};

